import { SampleBriefData } from '@/lib/types';

export const SAMPLE_FOUNDER_MD = `# GreenGrid Energy

## The Problem
Traditional energy grids are inefficient and carbon-intensive. The world needs smart, renewable-first energy infrastructure, but existing solutions are fragmented and expensive. With climate deadlines looming and energy costs soaring, we need a unified platform that can integrate renewable sources seamlessly.

## Target Market & GTM
Primary: Municipal utilities and energy cooperatives serving 10K-100K customers. Secondary: Commercial property managers and industrial facilities. GTM: Direct sales to utilities, partnerships with renewable installers, and a self-service platform for smaller customers.

## Current Traction
Pilot program with 3 municipal utilities showing 40% efficiency gains. $2M in LOIs from 8 utilities. Team includes 2 former utility executives and 3 energy PhDs. Patents filed for core grid optimization algorithms.

## 6-Month Goals
Launch commercial product with 5 paying utility customers. Achieve $500K ARR. Complete Series A fundraising of $8M. Expand team to 25 people including key sales and engineering hires.

## Financial Position
Current cash: $1.2M
Monthly burn: $180K
Runway: 6.7 months

## Key Risks & Assumptions
Regulatory approval timeline uncertainty. Competition from established grid operators. Key technical risk: scaling our optimization algorithms to handle larger grid networks. Market risk: utility procurement cycles are notoriously slow.

---
*Generated by Banyan - Transform founder instinct into investor-ready clarity*`;

export const SAMPLE_VC_MD = `## Investment Summary

**Stage:** Seed-ready
**Runway:** 6.7 months

### Key Highlights
- **Problem:** Traditional energy grids are inefficient and carbon-intensive. The world needs smart, renewable-first energy infrastructure, but existing solutions are fragmented and expensive...
- **Market:** Primary: Municipal utilities and energy cooperatives serving 10K-100K customers. Secondary: Commercial property managers and industrial facilities. GTM: Direct sales to utilities...
- **Traction:** Pilot program with 3 municipal utilities showing 40% efficiency gains. $2M in LOIs from 8 utilities. Team includes 2 former utility executives and 3 energy PhDs...

### Next 6 Months
Launch commercial product with 5 paying utility customers. Achieve $500K ARR. Complete Series A fundraising of $8M. Expand team to 25 people including key sales and engineering hires.

### Financial Health
Current cash: $1.2M
Monthly burn: $180K
Runway: 6.7 months

### Risk Assessment
Regulatory approval timeline uncertainty. Competition from established grid operators. Key technical risk: scaling our optimization algorithms to handle larger grid networks. Market risk: utility procurement cycles are notoriously slow.

---
*VC-ready summary generated by Banyan*`;

export const SAMPLE_BRIEF: SampleBriefData = {
  id: 'sample',
  name: 'GreenGrid Energy',
  stage: 'seed_ready',
  responses: {
    problem: 'Traditional energy grids are inefficient and carbon-intensive. The world needs smart, renewable-first energy infrastructure, but existing solutions are fragmented and expensive. With climate deadlines looming and energy costs soaring, we need a unified platform that can integrate renewable sources seamlessly.',
    customer: 'Primary: Municipal utilities and energy cooperatives serving 10K-100K customers. Secondary: Commercial property managers and industrial facilities. GTM: Direct sales to utilities, partnerships with renewable installers, and a self-service platform for smaller customers.',
    traction: 'Pilot program with 3 municipal utilities showing 40% efficiency gains. $2M in LOIs from 8 utilities. Team includes 2 former utility executives and 3 energy PhDs. Patents filed for core grid optimization algorithms.',
    milestone: 'Launch commercial product with 5 paying utility customers. Achieve $500K ARR. Complete Series A fundraising of $8M. Expand team to 25 people including key sales and engineering hires.',
    cash: 'Current cash: $1.2M\nMonthly burn: $180K\nRunway: 6.7 months',
    risk: 'Regulatory approval timeline uncertainty. Competition from established grid operators. Key technical risk: scaling our optimization algorithms to handle larger grid networks. Market risk: utility procurement cycles are notoriously slow.'
  },
  founderBrief: `# GreenGrid Energy

## The Problem
Traditional energy grids are inefficient and carbon-intensive. The world needs smart, renewable-first energy infrastructure, but existing solutions are fragmented and expensive. With climate deadlines looming and energy costs soaring, we need a unified platform that can integrate renewable sources seamlessly.

## Target Market & GTM
Primary: Municipal utilities and energy cooperatives serving 10K-100K customers. Secondary: Commercial property managers and industrial facilities. GTM: Direct sales to utilities, partnerships with renewable installers, and a self-service platform for smaller customers.

## Current Traction
Pilot program with 3 municipal utilities showing 40% efficiency gains. $2M in LOIs from 8 utilities. Team includes 2 former utility executives and 3 energy PhDs. Patents filed for core grid optimization algorithms.

## 6-Month Goals
Launch commercial product with 5 paying utility customers. Achieve $500K ARR. Complete Series A fundraising of $8M. Expand team to 25 people including key sales and engineering hires.

## Financial Position
Current cash: $1.2M
Monthly burn: $180K
Runway: 6.7 months

## Key Risks & Assumptions
Regulatory approval timeline uncertainty. Competition from established grid operators. Key technical risk: scaling our optimization algorithms to handle larger grid networks. Market risk: utility procurement cycles are notoriously slow.

---
*Generated by Banyan - Transform founder instinct into investor-ready clarity*`,
  vcSummary: `## Investment Summary

**Stage:** Seed-ready
**Runway:** 6.7 months

### Key Highlights
- **Problem:** Traditional energy grids are inefficient and carbon-intensive. The world needs smart, renewable-first energy infrastructure, but existing solutions are fragmented and expensive...
- **Market:** Primary: Municipal utilities and energy cooperatives serving 10K-100K customers. Secondary: Commercial property managers and industrial facilities. GTM: Direct sales to utilities...
- **Traction:** Pilot program with 3 municipal utilities showing 40% efficiency gains. $2M in LOIs from 8 utilities. Team includes 2 former utility executives and 3 energy PhDs...

### Next 6 Months
Launch commercial product with 5 paying utility customers. Achieve $500K ARR. Complete Series A fundraising of $8M. Expand team to 25 people including key sales and engineering hires.

### Financial Health
Current cash: $1.2M
Monthly burn: $180K
Runway: 6.7 months

### Risk Assessment
Regulatory approval timeline uncertainty. Competition from established grid operators. Key technical risk: scaling our optimization algorithms to handle larger grid networks. Market risk: utility procurement cycles are notoriously slow.

---
*VC-ready summary generated by Banyan*`
};
